# LAB | SQL Joins
## Challenge - Joining on multiple tables
#Write SQL queries to perform the following tasks using the Sakila database:
USE sakila;

#1. List the number of films per category.
SELECT c.name as 'Category', COUNT(fc.film_id) AS 'Number of films'
FROM category as c
LEFT JOIN film_category AS fc ON c.category_id = fc.category_id
GROUP BY c.name
ORDER BY c.name;

#2. Retrieve the store ID, city, and country for each store.
SELECT s.store_id, c.city, coun.country
FROM store as s
JOIN address as adr on s.address_id = adr.address_id
JOIN city as c on adr.city_id = c.city_id
JOIN country as coun on c.country_id = coun.country_id
ORDER BY s.store_id;

#3.  Calculate the total revenue generated by each store in dollars.
SELECT s.store_id, FORMAT(sum(p.amount),2) AS 'total revenue'
FROM store as s
LEFT JOIN customer AS c ON s.store_id = c.store_id
LEFT JOIN payment AS p ON c.customer_id = p.customer_id
GROUP BY s.store_id;

#4.  Determine the average running time of films for each category.
SELECT c.name as 'Category', FORMAT(AVG(f.length),0) AS 'Average running time'
FROM category as c
LEFT JOIN film_category AS fc ON c.category_id = fc.category_id
LEFT JOIN film as f ON fc.film_id = f.film_id
GROUP BY c.name
ORDER BY c.name;

#**Bonus**:
#5.  Identify the film categories with the longest average running time.
SELECT c.name as 'Category', FORMAT(AVG(f.length),0) AS 'Higher average running time of films'
FROM category as c
JOIN film_category AS fc ON c.category_id = fc.category_id
JOIN film as f ON fc.film_id = f.film_id
GROUP BY c.name
ORDER BY AVG(f.length) DESC
LIMIT 1;

#6.  Display the top 10 most frequently rented movies in descending order.
SELECT f.title AS 'Top 10 most frequently rented movies', count(inv.inventory_id) AS 'Number of rents'
FROM film f
JOIN inventory AS inv ON f.film_id = inv.film_id
JOIN rental AS ren ON inv.inventory_id = ren.inventory_id
GROUP BY f.title
ORDER BY count(inv.inventory_id) DESC
LIMIT 10;

#7. Determine if "Academy Dinosaur" can be rented from Store 1.
SELECT DISTINCT(f.title), rent.inventory_id, inv.store_id
FROM film f
JOIN inventory AS inv ON f.film_id = inv.film_id
JOIN rental AS rent ON inv.inventory_id = rent.inventory_id
WHERE f.title LIKE "Academy Dinosaur" AND inv.store_id = 1;

#8. Provide a list of all distinct film titles, along with their availability status in the inventory. 
#Include a column indicating whether each title is 'Available' or 'NOT available.' 
#Note that there are 42 titles that are not in the inventory, and this information can be obtained using a `CASE` statement combined with `IFNULL`."

SELECT DISTINCT(f.title),# rent.inventory_id, inv.store_id,
CASE
    WHEN inv.inventory_id IS NOT NULL THEN 'Available'
    ELSE 'Not available.'
END AS 'Status'
FROM film f
JOIN inventory AS inv ON f.film_id = inv.film_id
JOIN rental AS rent ON inv.inventory_id = rent.inventory_id
ORDER BY f.title;

/*#Here are some tips to help you successfully complete the lab:
***Tip 1***: This lab involves joins with multiple tables, which can be challenging. Take your time and follow the steps we discussed in class:
- Make sure you understand the relationships between the tables in the database. This will help you determine which tables to join and which columns to use in your joins.
- Identify a common column for both tables to use in the `ON` section of the join.
If there isn't a common column, you may need to add another table with a common column.
- Decide which table you want to use as the left table (immediately after `FROM`) and which will be the right table (immediately after `JOIN`).
- Determine which table you want to include all records from. This will help you decide which type of `JOIN` to use. 
If you want all records from the first table, use a `LEFT JOIN`. If you want all records from the second table, use a `RIGHT JOIN`. 
If you want records from both tables only where there is a match, use an `INNER JOIN`.
- Use table aliases to make your queries easier to read and understand. This is especially important when working with multiple tables.
- Write the query

***Tip 2***: Break down the problem into smaller, more manageable parts. For example, you might start by writing a query to retrieve data from just two tables before adding additional tables to the join. Test your queries as you go, and check the output carefully to make sure it matches what you expect. This process takes time, so be patient and go step by step to build your query incrementally.
*/